#pragma once

#undef PERMISSIVE_HOLD
#undef RETRO_TAPPING
#undef TAPPING_FORCE_HOLD
#undef TAPPING_TERM
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM 150
#define TAP_CODE_DELAY 10
#define TAP_HOLD_CAPS_DELAY 80

// start QMK squeezing
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT
// end QMK squeezing

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #define RGBLIGHT_EFFECT_SNAKE
    #define RGBLIGHT_EFFECT_STATIC_GRADIENT
    #define RGBLIGHT_EFFECT_TWINKLE
    #undef RGBLIGHT_EFFECT_ALTERNATING
    #undef RGBLIGHT_EFFECT_BREATHING
    #undef RGBLIGHT_EFFECT_CHRISTMAS
    #undef RGBLIGHT_EFFECT_KNIGHT
    #undef RGBLIGHT_EFFECT_RAINBOW_MOOD
    #undef RGBLIGHT_EFFECT_RGB_TEST

    // TODO is this the right thing to do? should these be here at all?
    #undef RGBLIGHT_LIMIT_VAL
    #undef RGBLIGHT_HUE_STEP
    #undef RGBLIGHT_SAT_STEP
    #undef RGBLIGHT_VAL_STEP
    #define RGBLIGHT_LIMIT_VAL 120
    #define RGBLIGHT_HUE_STEP 10
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 17
#endif
